name: turkify_bem
description: "by Berk Emre Mert"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.12
  file_picker: ^5.3.2
  http: '>=0.13.6 <2.0.0'
  image_picker: ^1.0.7
  intl: ^0.18.1
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  uuid: ^3.0.7
  flutter_colorpicker: ^1.0.3
  flutter_login: ^5.0.0
  dropdown_model_list: ^2.0.2
  flutter_svg: ^1.0.0
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3
  shared_preferences: ^2.2.2
  logging_appenders: ^1.2.0+1
  flutter_rating_bar: ^4.0.1
  latlng: ^1.0.0
  cached_network_image: ^3.3.1
  filter_list: ^1.0.2
  multi_selection_filter: ^0.0.6
  card_swiper: ^3.0.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.2
  loading_overlay: ^0.3.0
  rflutter_alert: ^2.0.7
  babstrap_settings_screen: ^0.1.6
  firebase_storage: ^11.6.9
  cupertino_icons: ^1.0.6
  firebase_app_check: ^0.2.1
  image_cropper: ^5.0.1
  flutter_webrtc: ^0.9.45
  cloud_firestore_web: ^3.4.3
  permission_handler: ^10.3.0
  bubble: ^1.2.1
  firebase_messaging: ^14.9.2
  free_english_dictionary: ^0.0.3
  simplytranslate: ^2.0.2
  auto_size_text: 3.0.0
  carousel_slider: 4.2.1
  collection: 1.18.0
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  json_path: 0.6.2
  page_transition: 2.1.0
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: 6.0.5
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  flutter_typeahead: ^4.0.0
  google_generative_ai:
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  lints: 3.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf


  assets:
    - .env
    - assets/callGrey.png
    - assets/callRed.png
    - assets/callOriginal.png
    - assets/callLightRed.png
    - assets/callGreen.png
    - assets/defaultProfilePicture.jpeg
    - assets/phoneRing.gif
    - assets/snail.png
    - assets/tutorsListingPage/yourTutorsMain.png
    - assets/tutorsListingPage/newTutorsRed.png
    - assets/tutorsListingPage/yourTutorsRedWhite.png
    - assets/studentsListingPage/chat.png
    - assets/studentsListingPage/video.png
    - assets/readingPage/icons/
    - assets/readingPage/images/


