// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkYrKupFZ5R26PsbNQ1WeW0-Yba99LzA4',
    appId: '1:780612013827:web:88a254cc3b6949b941e336',
    messagingSenderId: '780612013827',
    projectId: 'turkifyapp',
    authDomain: 'turkifyapp.firebaseapp.com',
    storageBucket: 'turkifyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvkqRZ0Rpof4xkFOEQTxrHLs4lBy4tzes',
    appId: '1:780612013827:android:b13280fd150e7ecf41e336',
    messagingSenderId: '780612013827',
    projectId: 'turkifyapp',
    storageBucket: 'turkifyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDLn8pTy8YBfFaQc8d51u_Vlx-KH8fCVc',
    appId: '1:780612013827:ios:6e56824af248b04f41e336',
    messagingSenderId: '780612013827',
    projectId: 'turkifyapp',
    storageBucket: 'turkifyapp.appspot.com',
    iosBundleId: 'com.example.turkifyBem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDLn8pTy8YBfFaQc8d51u_Vlx-KH8fCVc',
    appId: '1:780612013827:ios:b09c166808d9cd1f41e336',
    messagingSenderId: '780612013827',
    projectId: 'turkifyapp',
    storageBucket: 'turkifyapp.appspot.com',
    iosBundleId: 'com.example.turkifyBem.RunnerTests',
  );
}
